import React, {useEffect} from 'react'
import Head from "next/head";
import { getSkin } from './api/api'

// Components

import { Canvas } from "react-three-fiber"
import { HTML } from "drei"

const HTMLContent = () => {
  return (
    <section>
    <Html fullscreen>
      <div className="container">
        <h1 className="title">Hi</h1>
      </div>
    </Html>
    </section>
  )
}


function Home({data}) {
  useEffect(() => {
   getSkin(data);
  }, []);

  return (
    <div>
      <Head>
        <title>NextMC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
    </div>
  );
}

export async function getStaticProps() {
  // Fetch UUID from username
  const getID = await fetch(
    `https://api.mojang.com/users/profiles/minecraft/outraved`
  );
  const uuidResult = await getID.json();
  const id = await uuidResult.id;

  // Fetch skin for given UUID
  const res = await fetch(
    `https://sessionserver.mojang.com/session/minecraft/profile/${id}`
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}

export default Home;
