import React, {useEffect} from 'react'
import Head from "next/head";
import { getSkin } from './api/api'
import Box from "../components/box"
import { Canvas } from 'react-three-fiber'

function Home({data}) {
  useEffect(() => {
   getSkin(data);
  }, []);

  // https://github.com/pmndrs/react-three-next Trying this next for implementing three.js
  return (
    <div>
      <Head>
        <title>NextMC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Canvas
      colorManagement
      camera={{
        position: [-5, 7, 11],
        fov: 75
      }}
    >
      {/* Lights */}
      <rectAreaLight
        intensity={3}
        position={[0, 1, 10]}
        width={50}
        height={50}
      />
      {/* The Ball and stand */}
      <group position={[0, -1, 0]}>
        <Box/>
      </group>
    </Canvas>
    </div>
  );
}

export async function getStaticProps() {
  // Fetch UUID from username
  const getID = await fetch(
    `https://api.mojang.com/users/profiles/minecraft/outraved`
  );
  const uuidResult = await getID.json();
  const id = await uuidResult.id;

  // Fetch skin for given UUID
  const res = await fetch(
    `https://sessionserver.mojang.com/session/minecraft/profile/${id}`
  );
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}

export default Home;
